site_name: LiteLoaderBDS
site_url: https://docs.litebds.com

nav:
  - Languages:
    - English: javascript:changeLanguage('en')
    - 中文: javascript:changeLanguage('zh')

  - Basics:
    - index.md
    - installation/windows.md
    - usage.md
    - faq.md

  - Development: https://github.com/LiteLDev/LiteLoaderBDS/wiki

theme:
  name: readthedocs
extra_javascript:
  - js/script.js

use_directory_urls: false

markdown_extensions:
  - admonition:
  - codehilite:

plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
        zh:
          name: 中文
      nav_translations:
        zh:
          Languages: 语言
          Basics: 基础
          Development: 开发
