site_name: LiteLoaderBDS 3
site_url: https://docs.litebds.com
repo_url: https://github.com/LiteLDev/LiteLoaderBDS
edit_uri: edit/v3/docs/
copyright: Copyright (c) 2023 <a href="https://github.com/LiteLDev">LiteLDev</a>

nav:
  - Languages:
    - English: javascript:changeLanguage('en')
    - 中文: javascript:changeLanguage('zh')

  - Basics:
    - index.md
    - installation/windows.md
    - usage.md
    - faq.md

  - Modules:
    - LLMoney: https://llmoney.docs.litebds.com

  - Development:
    - development/overview.md

theme:
  name: readthedocs
extra_javascript:
  - js/script.js

markdown_extensions:
  - admonition:
  - codehilite:

plugins:
  - i18n:
      default_language: en
      languages:
        en:
          name: English
        zh:
          name: 简体中文
      nav_translations:
        zh:
          Languages: 语言
          Basics: 基础
          Modules: 组件
          Development: 开发
